# Generated by Django 5.1 on 2024-10-09 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DeliveryPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "batch_target",
                    models.CharField(
                        choices=[
                            ("SAME_DAY", "same day"),
                            ("PREVIOUS_DAY", "previous day"),
                        ],
                        default="SAME_DAY",
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("address", models.CharField(max_length=400)),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["name"], name="boulange_de_name_e978e2_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="DeliveryDate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "delivery_point",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="boulange.deliverypoint",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("email", models.CharField(max_length=200)),
                ("active", models.BooleanField(default=True)),
                (
                    "default_delivery_point",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="boulange.deliverypoint",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Ingredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("unit", models.CharField(max_length=10)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["name"], name="boulange_in_name_c6657a_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="boulange.customer",
                    ),
                ),
                (
                    "delivery_date",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="boulange.deliverydate",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("ref", models.CharField(max_length=20)),
                ("price", models.DecimalField(decimal_places=2, max_digits=5)),
                ("active", models.BooleanField(default=True)),
                ("coef", models.FloatField(default=1)),
                ("nb_units", models.IntegerField(default=1)),
                (
                    "orig_recipe",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="boulange.recipe",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField()),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="boulange.order"
                    ),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="boulange.recipe",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RecipeLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.FloatField()),
                (
                    "ingredient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="boulange.ingredient",
                    ),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="boulange.recipe",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(fields=["name"], name="boulange_cu_name_f6a126_idx"),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(fields=["email"], name="boulange_cu_email_a59615_idx"),
        ),
        migrations.AddIndex(
            model_name="recipe",
            index=models.Index(fields=["name"], name="boulange_re_name_2c05e2_idx"),
        ),
        migrations.AddIndex(
            model_name="recipe",
            index=models.Index(fields=["ref"], name="boulange_re_ref_e7550c_idx"),
        ),
    ]
