# Generated by Django 5.1.4 on 2025-01-16 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boulange", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customer",
            options={"verbose_name": "Client"},
        ),
        migrations.AlterModelOptions(
            name="deliverydate",
            options={
                "ordering": ["date", "weekly_delivery"],
                "verbose_name": "Date de livraison",
                "verbose_name_plural": "Dates de livraison",
            },
        ),
        migrations.AlterModelOptions(
            name="order",
            options={"verbose_name": "Commande"},
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"verbose_name": "Produit"},
        ),
        migrations.AlterModelOptions(
            name="weeklydelivery",
            options={
                "ordering": ["day_of_week", "customer"],
                "verbose_name": "Livraison hebdo",
                "verbose_name_plural": "Livraisons hebdo",
            },
        ),
        migrations.AlterField(
            model_name="customer",
            name="display_name",
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="pro_discount_percentage",
            field=models.FloatField(blank=True, default=5.0),
        ),
        migrations.AlterField(
            model_name="product",
            name="ref",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
