# Generated by Django 5.1.4 on 2025-02-12 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boulange", "0002_alter_customer_options_alter_deliverydate_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customer",
            options={"ordering": ["display_name"], "verbose_name": "Client"},
        ),
        migrations.AlterModelOptions(
            name="ingredient",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="order",
            options={"ordering": ["-delivery_date", "customer"], "verbose_name": "Commande"},
        ),
        migrations.AlterModelOptions(
            name="orderline",
            options={"ordering": ["product__name"]},
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["name"], "verbose_name": "Produit"},
        ),
        migrations.AlterModelOptions(
            name="productline",
            options={"ordering": ["ingredient__name"]},
        ),
        migrations.AddField(
            model_name="customer",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="deliverydate",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="weeklydelivery",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
    ]
