# Generated by Django 5.1 on 2024-08-18 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boulange", "0002_auto_20240817_0858"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(fields=["name"], name="boulange_cu_name_f6a126_idx"),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(fields=["email"], name="boulange_cu_email_a59615_idx"),
        ),
        migrations.AddIndex(
            model_name="deliverypoint",
            index=models.Index(fields=["name"], name="boulange_de_name_e978e2_idx"),
        ),
        migrations.AddIndex(
            model_name="ingredient",
            index=models.Index(fields=["name"], name="boulange_in_name_c6657a_idx"),
        ),
        migrations.AddIndex(
            model_name="recipe",
            index=models.Index(fields=["name"], name="boulange_re_name_2c05e2_idx"),
        ),
        migrations.AddIndex(
            model_name="recipe",
            index=models.Index(fields=["ref"], name="boulange_re_ref_e7550c_idx"),
        ),
    ]
