# Generated by Django 5.1 on 2024-08-18 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boulange", "0003_customer_boulange_cu_name_f6a126_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="coef",
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name="recipe",
            name="orig_recipe",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="boulange.recipe",
            ),
        ),
    ]
