# Generated by Django 5.1.4 on 2025-02-13 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boulange", "0003_alter_customer_options_alter_ingredient_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="cooked_by_two",
            field=models.BooleanField(default=False),
        ),
    ]
