# Generated by Django 5.1 on 2024-10-15 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boulange", "0003_add_recipes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="default_delivery_point",
        ),
        migrations.AddField(
            model_name="customer",
            name="is_professional",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customer",
            name="pro_discount_percentage",
            field=models.FloatField(default=5.0),
        ),
        migrations.AddField(
            model_name="deliverypoint",
            name="can_order_here_from_website",
            field=models.BooleanField(default=True),
        ),
    ]
