# Generated by Django 5.1 on 2024-08-18 07:12

from django.db import migrations
    
def populate_recipes(apps, schema_editor):
    Ingredient = apps.get_model("boulange", "Ingredient")
    Recipe = apps.get_model("boulange", "Recipe")
    RecipeLine = apps.get_model("boulange", "RecipeLine")

    # Nature
    ref_GN = Recipe(name='Semi-complet nature (1 kg)',
                    ref='GN',
                    price=5)
    ref_GN.save()
    GN_ingredients = [(Ingredient.objects.get(name="Farine blé"), 637),
                      (Ingredient.objects.get(name="Eau"), 414),
                      (Ingredient.objects.get(name="Levain"), 178),
                      (Ingredient.objects.get(name="Sel"), 11)]
    for ing in GN_ingredients:
        RecipeLine(recipe=ref_GN,
                   ingredient=ing[0],
                   quantity=ing[1]).save()
    ref_TGN = Recipe(name='Semi-complet nature (2 kg)',
                     ref='TGN',
                     price=10,
                     orig_recipe=ref_GN,
                     coef=2)
    ref_TGN.save()
    ref_PN = Recipe(name='Semi-complet nature (500 g)',
                     ref='TGN',
                     price=2.7,
                     orig_recipe=ref_GN,
                     coef=0.5)
    ref_TGN.save()
    # Lin
    ref_GL = Recipe(name='Semi-complet Lin (1 kg)',
                    ref='CGLi',
                    price=6.5)
    ref_GL.save()
    GL_ingredients = [(Ingredient.objects.get(name="Farine blé"), 585),
                      (Ingredient.objects.get(name="Eau"), 409),
                      (Ingredient.objects.get(name="Levain"), 164),
                      (Ingredient.objects.get(name="Sel"), 11),
                      (Ingredient.objects.get(name="Graines lin"), 76)]
    for ing in GL_ingredients:
        RecipeLine(recipe=ref_GL,
                   ingredient=ing[0],
                   quantity=ing[1]).save()
    ref_TGL = Recipe(name='Semi-complet lin (2 kg)',
                     ref='CTGLi',
                     price=13,
                     orig_recipe=ref_GL,
                     coef=2)
    ref_TGL.save()
    ref_PL = Recipe(name='Semi-complet lin (500 g)',
                     ref='CPLi',
                     price=3.5,
                    orig_recipe=ref_GL,
                     coef=0.5)
    ref_PL.save()
    # Kasha
    ref_GK = Recipe(name='Semi-complet Kasha (1 kg)',
                    ref='CGK',
                    price=6.5)
    ref_GK.save()
    GK_ingredients = [(Ingredient.objects.get(name="Farine blé"), 599),
                      (Ingredient.objects.get(name="Eau"), 389),
                      (Ingredient.objects.get(name="Levain"), 168),
                      (Ingredient.objects.get(name="Sel"), 11),
                      (Ingredient.objects.get(name="Graines kasha"), 78)]
    for ing in GK_ingredients:
        RecipeLine(recipe=ref_GK,
                   ingredient=ing[0],
                   quantity=ing[1]).save()
    ref_TGK = Recipe(name='Semi-complet kasha (2 kg)',
                     ref='CTGK',
                     price=13,
                     orig_recipe=ref_GK,
                     coef=2)
    ref_TGK.save()
    ref_PK = Recipe(name='Semi-complet kasha (500 g)',
                     ref='CPK',
                     price=3.5,
                    orig_recipe=ref_GK,
                     coef=0.5)
    ref_PK.save()
    # sarrasin
    ref_GSa = Recipe(name='Sarrasin 100% (800 g)',
                    ref='GSa',
                    price=6.5)
    ref_GSa.save()
    GSa_ingredients = [(Ingredient.objects.get(name="Farine sarrasin"), 549*0.8),
                       (Ingredient.objects.get(name="Eau"), 549*0.8),
                       (Ingredient.objects.get(name="Levain"), 165*0.8),
                       (Ingredient.objects.get(name="Sel"), 11*0.8)]
    for ing in GSa_ingredients:
        RecipeLine(recipe=ref_GSa,
                   ingredient=ing[0],
                   quantity=ing[1]).save()
    ref_TGSa = Recipe(name='Sarrasin 100% (1,6 kg)',
                      ref='TGSa',
                      price=13,
                      orig_recipe=ref_GSa,
                      coef=2)
    ref_TGSa.save()
    ref_PSa = Recipe(name='Sarrasin 100% (400 g)',
                     ref='PSa',
                     price=3.5,
                     orig_recipe=ref_GSa,
                     coef=0.5)
    ref_PSa.save()
    # seigle
    ref_GSe = Recipe(name='Seigle 100% (800 g)',
                    ref='GSe',
                    price=6.5)
    ref_GSe.save()
    GSe_ingredients = [(Ingredient.objects.get(name="Farine blé"), 197*0.8),
                       (Ingredient.objects.get(name="Farine seigle"), 461*0.8),
                       (Ingredient.objects.get(name="Eau"), 428*0.8),
                       (Ingredient.objects.get(name="Levain"), 184*0.8),
                       (Ingredient.objects.get(name="Sel"), 12*0.8)]
    for ing in GSe_ingredients:
        RecipeLine(recipe=ref_GSe,
                   ingredient=ing[0],
                   quantity=ing[1]).save()
    ref_TGSe = Recipe(name='Seigle 100% (1,6 kg)',
                      ref='TGSe',
                      price=13,
                      orig_recipe=ref_GSe,
                      coef=2)
    ref_TGSe.save()
    ref_PSe = Recipe(name='Seigle 100% (400 g)',
                     ref='PSe',
                     price=3.5,
                     orig_recipe=ref_GSe,
                     coef=0.5)
    ref_PSe.save()
    


class Migration(migrations.Migration):

    dependencies = [
        ("boulange", "0004_recipe_coef_recipe_orig_recipe"),
    ]

    operations = [
        migrations.RunPython(populate_recipes)
    ]
