# Generated by Django 5.1 on 2024-10-15 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boulange", "0004_remove_customer_default_delivery_point_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ingredient",
            name="soaking_coef",
            field=models.FloatField(default=1),
        ),
    ]
