# Generated by Django 5.1.4 on 2025-02-13 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("boulange", "0004_product_cooked_by_two"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="cooked_by_two",
            new_name="baked_by_two",
        ),
    ]
