# Generated by Django 5.1 on 2024-10-15 09:13

from django.db import migrations

from ..models import Ingredient


def edit_ingredients(apps, schema_editor):
    raisins = Ingredient.objects.get(name="Raisins secs")
    raisins.needs_soaking = True
    raisins.save()
    Ingredient.objects.get(name="Lait de riz").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("boulange", "0005_ingredient_soaking_coef"),
    ]

    operations = [migrations.RunPython(edit_ingredients)]
