# Generated by Django 5.1 on 2024-08-18 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("boulange", "0005_add_recipes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="delivery_point",
        ),
    ]
