# Generated by Django 5.1.4 on 2025-02-13 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boulange", "0005_rename_cooked_by_two_product_baked_by_two"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="display_priority",
            field=models.IntegerField(default=0),
        ),
    ]
