# Generated by Django 5.1 on 2024-10-08 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boulange", "0006_remove_order_delivery_point"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliverypoint",
            name="batch_target",
            field=models.CharField(
                choices=[("SAME_DAY", "same day"), ("PREVIOUS_DAY", "previous day")],
                default="SAME_DAY",
                max_length=20,
            ),
        ),
    ]
