# Generated by Django 5.1.4 on 2025-04-03 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boulange", "0006_product_display_priority"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_bread",
            field=models.BooleanField(default=False),
        ),
    ]
