# Generated by Django 5.1 on 2024-10-15 10:09

from django.db import migrations

from ..models import Ingredient, Product, ProductLine


def edit_brioches(apps, schema_editor):
    riz = Ingredient(
        name="Flocons de riz",
        unit="g",
        needs_soaking=True,
        soaking_coef=10,
        per_unit_price=3.95,
    )
    riz.save()
    eau = Ingredient.objects.get(name="Eau")
    for ref in ["BR", "BC"]:
        brioche = Product.objects.get(ref=ref)
        brioche.productline_set.filter(ingredient__name="Lait").get().delete()
        ProductLine(product=brioche, ingredient=riz, quantity=26.91).save()
        ProductLine(product=brioche, ingredient=eau, quantity=269.1).save()


class Migration(migrations.Migration):

    dependencies = [
        ("boulange", "0006_ingredients_edit"),
    ]

    operations = [migrations.RunPython(edit_brioches)]
