# Generated by Django 5.1.4 on 2025-04-03 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boulange", "0007_product_is_bread"),
    ]

    operations = [
        migrations.CreateModel(
            name="Settings",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200, unique=True)),
                ("value", models.CharField(max_length=200)),
            ],
            options={
                "verbose_name": "Paramètre",
            },
        ),
    ]
