# Generated by Django 5.1 on 2024-10-16 05:53

from django.db import migrations

from ..models import Ingredient


def rename_levain(apps, schema_editor):
    levain = Ingredient.objects.get(name="Levain")
    levain.name = "Levain froment"
    levain.save()


class Migration(migrations.Migration):

    dependencies = [
        ("boulange", "0007_edit_brioches"),
    ]

    operations = [migrations.RunPython(rename_levain)]
