# Generated by Django 5.1 on 2024-11-27 15:17

from django.db import migrations
from ..models import Product


def divide_brioches(apps, schema_editor):
    br1 = Product.objects.get(name="Brioche raisin")
    br2 = Product.objects.get(name="Brioche chocolat")
    for br in [br1, br2]:
        for line in br.productline_set.all():
            line.quantity = line.quantity / 2
            line.save()


class Migration(migrations.Migration):

    dependencies = [
        ("boulange", "0008_rename_levain"),
    ]

    operations = [migrations.RunPython(divide_brioches)]
