# Generated by Django 5.2.1 on 2025-07-20 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boulange", "0008_settings"),
    ]

    operations = [
        migrations.AddField(
            model_name="ingredient",
            name="soaking_ingredient",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="boulange.ingredient"),
        ),
    ]
