# Generated by Django 5.2.1 on 2025-07-20 20:44

from django.db import migrations


def set_soaking_ingredient_value(apps, schema_editor):
    Ingredient = apps.get_model("boulange", "Ingredient")
    try:
        water = Ingredient.objects.get(name="Eau")
    except Ingredient.DoesNotExist:
        # if not found this is a test
        return
    for ing in Ingredient.objects.all():
        if ing.needs_soaking:
            ing.soaking_ingredient = water
            ing.save()


class Migration(migrations.Migration):

    dependencies = [
        ("boulange", "0009_ingredient_soaking_ingredient"),
    ]

    operations = [migrations.RunPython(set_soaking_ingredient_value)]
