# Generated by Django 5.2.1 on 2025-07-20 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("boulange", "0010_populate_soaking_ingredient"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ingredient",
            name="needs_soaking",
        ),
    ]
