# Generated by Django 5.1.4 on 2024-12-18 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boulange", "0010_remove_customer_boulange_cu_name_f6a126_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="delivery_point",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="boulange.deliverypoint",
            ),
        ),
    ]
