# Generated by Django 5.1.4 on 2024-12-15 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boulange", "0010_remove_customer_boulange_cu_name_f6a126_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliverypoint",
            name="initial_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
