# Generated by Django 5.1.4 on 2024-12-18 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("boulange", "0011_customer_delivery_point"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="deliverypoint",
            name="boulange_de_name_e978e2_idx",
        ),
        migrations.RemoveField(
            model_name="deliverypoint",
            name="active",
        ),
        migrations.RemoveField(
            model_name="deliverypoint",
            name="name",
        ),
    ]
