# Generated by Django 5.2.1 on 2025-07-26 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boulange", "0011_remove_ingredient_needs_soaking"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="baked_by_batch",
            field=models.BooleanField(default=False),
        ),
    ]
