# Generated by Django 5.2.1 on 2025-07-26 10:01

from django.db import migrations


def set_baked_by_batch(apps, schema_editor):
    Product = apps.get_model("boulange", "Product")
    for product in Product.objects.all():
        if product.baked_by_two:
            product.baked_by_batch = True
            product.nb_units = 2
            product.coef *= 2
            product.save()


class Migration(migrations.Migration):

    dependencies = [
        ("boulange", "0012_product_baked_by_batch"),
    ]

    operations = [migrations.RunPython(set_baked_by_batch)]
