# Generated by Django 5.2.1 on 2025-07-26 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("boulange", "0013_migrate_baked_by_two"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="baked_by_two",
        ),
    ]
