# Generated by Django 5.1.4 on 2024-12-21 14:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boulange", "0013_alter_deliverydate_delivery_point_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="address",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="batch_target",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="can_order_here_from_website",
        ),
        migrations.RemoveField(
            model_name="deliverydate",
            name="delivery_point",
        ),
        migrations.CreateModel(
            name="DeliveryDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "batch_target",
                    models.CharField(
                        choices=[
                            ("SAME_DAY", "same day"),
                            ("PREVIOUS_DAY", "previous day"),
                        ],
                        default="SAME_DAY",
                        max_length=20,
                    ),
                ),
                ("address", models.CharField(blank=True, max_length=400, null=True)),
                ("can_order_here_from_website", models.BooleanField(default=True)),
                (
                    "day_of_week",
                    models.IntegerField(
                        choices=[
                            (0, "lundi"),
                            (1, "mardi"),
                            (2, "mercredi"),
                            (3, "jeudi"),
                            (4, "vendredi"),
                            (5, "samedi"),
                            (6, "dimanche"),
                        ]
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="deliverydate",
            name="delivery_day",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="boulange.deliveryday",
            ),
        ),
    ]
