# Generated by Django 5.2.1 on 2025-10-12 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boulange", "0014_remove_product_baked_by_two"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="validated",
            field=models.BooleanField(default=True),
        ),
    ]
