# Generated by Django 5.1.4 on 2024-12-21 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "boulange",
            "0014_remove_customer_address_remove_customer_batch_target_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="deliverydate",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
