# Generated by Django 5.2.1 on 2025-11-01 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boulange", "0015_order_validated"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="available_fridays",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="product",
            name="available_mondays",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="product",
            name="available_saturdays",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="product",
            name="available_sundays",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="product",
            name="available_thursdays",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="product",
            name="available_tuesdays",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="product",
            name="available_wednesdays",
            field=models.BooleanField(default=True),
        ),
    ]
