# Generated by Django 5.2.1 on 2025-11-01 07:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boulange", "0016_product_available_fridays_product_available_mondays_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="weeklydelivery",
            name="allowed_customers",
            field=models.ManyToManyField(related_name="private_weekly_deliveries", to=settings.AUTH_USER_MODEL),
        ),
    ]
