# Generated by Django 5.2.1 on 2025-11-02 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("boulange", "0017_weeklydelivery_allowed_customers"),
    ]

    operations = [
        migrations.RenameField(
            model_name="weeklydelivery",
            old_name="can_order_here_from_website",
            new_name="public_delivery_point",
        ),
    ]
