# Generated by Django 5.1.4 on 2024-12-31 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boulange", "0017_order_delivery_day_alter_order_delivery_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="delivery_day",
        ),
        migrations.RemoveField(
            model_name="deliverydate",
            name="delivery_day",
        ),
        migrations.AlterModelOptions(
            name="deliverydate",
            options={"ordering": ["date", "weekly_delivery"]},
        ),
        migrations.AddField(
            model_name="customer",
            name="address",
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="delivery_date",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="boulange.deliverydate",
            ),
        ),
        migrations.CreateModel(
            name="WeeklyDelivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                (
                    "batch_target",
                    models.CharField(
                        choices=[
                            ("SAME_DAY", "same day"),
                            ("PREVIOUS_DAY", "previous day"),
                        ],
                        default="SAME_DAY",
                        max_length=20,
                    ),
                ),
                ("can_order_here_from_website", models.BooleanField(default=True)),
                (
                    "day_of_week",
                    models.IntegerField(
                        choices=[
                            (0, "lundi"),
                            (1, "mardi"),
                            (2, "mercredi"),
                            (3, "jeudi"),
                            (4, "vendredi"),
                            (5, "samedi"),
                            (6, "dimanche"),
                        ]
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="boulange.customer",
                    ),
                ),
            ],
            options={
                "ordering": ["day_of_week", "customer"],
            },
        ),
        migrations.AddField(
            model_name="deliverydate",
            name="weekly_delivery",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="boulange.weeklydelivery",
            ),
        ),
        migrations.DeleteModel(
            name="DeliveryDay",
        ),
    ]
