# Generated by Django 5.2.1 on 2025-11-11 15:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boulange", "0018_rename_can_order_here_from_website_weeklydelivery_public_delivery_point"),
    ]

    operations = [
        migrations.AlterField(
            model_name="weeklydelivery",
            name="allowed_customers",
            field=models.ManyToManyField(blank=True, related_name="private_weekly_deliveries", to=settings.AUTH_USER_MODEL),
        ),
    ]
