# Generated by Django 5.2.8 on 2025-11-29 20:53

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boulange", "0019_alter_weeklydelivery_allowed_customers"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResetAccountToken",
            fields=[
                ("token", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created", models.DateTimeField()),
            ],
        ),
    ]
