# Generated by Django 5.2.8 on 2025-11-29 21:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boulange", "0020_resetaccounttoken"),
    ]

    operations = [
        migrations.AddField(
            model_name="resetaccounttoken",
            name="customer",
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
