# Generated by Django 5.2.8 on 2025-11-29 21:12

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boulange", "0021_resetaccounttoken_customer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resetaccounttoken",
            name="created",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
