# Generated by Django 5.2.8 on 2025-12-10 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boulange", "0023_checkout_order_checkout"),
    ]

    operations = [
        migrations.AddField(
            model_name="weeklydelivery",
            name="online_payment",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="checkout",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="boulange.checkout"),
        ),
    ]
