# Generated by Django 5.2.8 on 2026-03-04 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boulange", "0024_weeklydelivery_online_payment_alter_order_checkout"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="checkout",
            options={"verbose_name": "Panier"},
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["-display_priority", "name"], "verbose_name": "Produit"},
        ),
        migrations.AddField(
            model_name="ingredient",
            name="decimal_round",
            field=models.BooleanField(default=True),
        ),
    ]
