# Generated by Django 5.2.8 on 2026-03-11 09:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boulange", "0025_alter_checkout_options_alter_product_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="checkout",
            name="customer",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name="order",
            name="delivery_date",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="boulange.deliverydate"),
        ),
        migrations.AlterField(
            model_name="product",
            name="orig_product",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="boulange.product"),
        ),
        migrations.AlterField(
            model_name="productline",
            name="ingredient",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="boulange.ingredient"),
        ),
        migrations.AlterField(
            model_name="weeklydelivery",
            name="customer",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
