# Generated by Django 5.2.8 on 2026-06-18 21:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boulange", "0026_alter_checkout_customer_alter_order_delivery_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resetaccounttoken",
            name="created",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterUniqueTogether(
            name="deliverydate",
            unique_together={("weekly_delivery", "date")},
        ),
    ]
