# Generated by Django 5.2.15 on 2026-06-24 18:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boulange", "0027_alter_resetaccounttoken_created_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="checkout",
            options={"verbose_name": "Panier", "verbose_name_plural": "Paniers"},
        ),
        migrations.AlterModelOptions(
            name="customer",
            options={"ordering": ["display_name"], "verbose_name": "Client", "verbose_name_plural": "Clients"},
        ),
        migrations.AlterModelOptions(
            name="ingredient",
            options={"ordering": ["name"], "verbose_name": "Ingrédient", "verbose_name_plural": "Ingrédients"},
        ),
        migrations.AlterModelOptions(
            name="order",
            options={"ordering": ["-delivery_date", "customer"], "verbose_name": "Commande", "verbose_name_plural": "Commandes"},
        ),
        migrations.AlterModelOptions(
            name="orderline",
            options={"ordering": ["product__name"], "verbose_name": "Ligne de commande", "verbose_name_plural": "Lignes de commande"},
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["-display_priority", "name"], "verbose_name": "Produit", "verbose_name_plural": "Produits"},
        ),
        migrations.AlterModelOptions(
            name="productline",
            options={"ordering": ["ingredient__name"], "verbose_name": "Ligne de recette", "verbose_name_plural": "Lignes de recette"},
        ),
        migrations.AlterModelOptions(
            name="settings",
            options={"verbose_name": "Paramètre", "verbose_name_plural": "Paramètres"},
        ),
        migrations.AlterField(
            model_name="checkout",
            name="customer",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name="Client"),
        ),
        migrations.AlterField(
            model_name="checkout",
            name="remote_id",
            field=models.CharField(max_length=64, verbose_name="Identifiant SumUp"),
        ),
        migrations.AlterField(
            model_name="customer",
            name="address",
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name="Adresse"),
        ),
        migrations.AlterField(
            model_name="customer",
            name="display_name",
            field=models.CharField(max_length=200, unique=True, verbose_name="Nom affiché"),
        ),
        migrations.AlterField(
            model_name="customer",
            name="is_professional",
            field=models.BooleanField(default=False, verbose_name="Professionnel"),
        ),
        migrations.AlterField(
            model_name="customer",
            name="notes",
            field=models.TextField(blank=True, null=True, verbose_name="Notes"),
        ),
        migrations.AlterField(
            model_name="customer",
            name="pro_discount_percentage",
            field=models.FloatField(blank=True, default=5.0, verbose_name="Remise pro (%)"),
        ),
        migrations.AlterField(
            model_name="deliverydate",
            name="active",
            field=models.BooleanField(default=True, verbose_name="Actif"),
        ),
        migrations.AlterField(
            model_name="deliverydate",
            name="date",
            field=models.DateField(verbose_name="Date"),
        ),
        migrations.AlterField(
            model_name="deliverydate",
            name="notes",
            field=models.TextField(blank=True, null=True, verbose_name="Notes"),
        ),
        migrations.AlterField(
            model_name="deliverydate",
            name="weekly_delivery",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="boulange.weeklydelivery", verbose_name="Livraison hebdo"),
        ),
        migrations.AlterField(
            model_name="ingredient",
            name="decimal_round",
            field=models.BooleanField(default=True, verbose_name="Arrondi décimal"),
        ),
        migrations.AlterField(
            model_name="ingredient",
            name="name",
            field=models.CharField(max_length=200, verbose_name="Nom"),
        ),
        migrations.AlterField(
            model_name="ingredient",
            name="per_unit_price",
            field=models.DecimalField(decimal_places=3, help_text="prix par kg, litre ou unité", max_digits=5, verbose_name="Prix unitaire"),
        ),
        migrations.AlterField(
            model_name="ingredient",
            name="soaking_coef",
            field=models.FloatField(default=1, verbose_name="Coefficient de trempage"),
        ),
        migrations.AlterField(
            model_name="ingredient",
            name="soaking_ingredient",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="boulange.ingredient", verbose_name="Ingrédient de trempage"),
        ),
        migrations.AlterField(
            model_name="ingredient",
            name="unit",
            field=models.CharField(max_length=10, verbose_name="Unité"),
        ),
        migrations.AlterField(
            model_name="order",
            name="checkout",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="boulange.checkout", verbose_name="Panier"),
        ),
        migrations.AlterField(
            model_name="order",
            name="customer",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name="Client"),
        ),
        migrations.AlterField(
            model_name="order",
            name="delivery_date",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="boulange.deliverydate", verbose_name="Date de livraison"),
        ),
        migrations.AlterField(
            model_name="order",
            name="notes",
            field=models.TextField(blank=True, null=True, verbose_name="Notes"),
        ),
        migrations.AlterField(
            model_name="order",
            name="validated",
            field=models.BooleanField(default=True, verbose_name="Validée"),
        ),
        migrations.AlterField(
            model_name="orderline",
            name="order",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="lines", to="boulange.order", verbose_name="Commande"),
        ),
        migrations.AlterField(
            model_name="orderline",
            name="product",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="boulange.product", verbose_name="Produit"),
        ),
        migrations.AlterField(
            model_name="orderline",
            name="quantity",
            field=models.IntegerField(verbose_name="Quantité"),
        ),
        migrations.AlterField(
            model_name="product",
            name="active",
            field=models.BooleanField(default=True, verbose_name="Actif"),
        ),
        migrations.AlterField(
            model_name="product",
            name="available_fridays",
            field=models.BooleanField(default=True, verbose_name="Disponible le vendredi"),
        ),
        migrations.AlterField(
            model_name="product",
            name="available_mondays",
            field=models.BooleanField(default=True, verbose_name="Disponible le lundi"),
        ),
        migrations.AlterField(
            model_name="product",
            name="available_saturdays",
            field=models.BooleanField(default=True, verbose_name="Disponible le samedi"),
        ),
        migrations.AlterField(
            model_name="product",
            name="available_sundays",
            field=models.BooleanField(default=True, verbose_name="Disponible le dimanche"),
        ),
        migrations.AlterField(
            model_name="product",
            name="available_thursdays",
            field=models.BooleanField(default=True, verbose_name="Disponible le jeudi"),
        ),
        migrations.AlterField(
            model_name="product",
            name="available_tuesdays",
            field=models.BooleanField(default=True, verbose_name="Disponible le mardi"),
        ),
        migrations.AlterField(
            model_name="product",
            name="available_wednesdays",
            field=models.BooleanField(default=True, verbose_name="Disponible le mercredi"),
        ),
        migrations.AlterField(
            model_name="product",
            name="baked_by_batch",
            field=models.BooleanField(default=False, verbose_name="Cuit par lot entier"),
        ),
        migrations.AlterField(
            model_name="product",
            name="coef",
            field=models.FloatField(default=1, verbose_name="Coefficient"),
        ),
        migrations.AlterField(
            model_name="product",
            name="display_priority",
            field=models.IntegerField(default=0, verbose_name="Priorité d'affichage"),
        ),
        migrations.AlterField(
            model_name="product",
            name="is_bread",
            field=models.BooleanField(default=False, verbose_name="Produit de type pain"),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=200, verbose_name="Nom"),
        ),
        migrations.AlterField(
            model_name="product",
            name="nb_units",
            field=models.IntegerField(default=1, verbose_name="Nombre d'unités"),
        ),
        migrations.AlterField(
            model_name="product",
            name="notes",
            field=models.TextField(blank=True, null=True, verbose_name="Notes"),
        ),
        migrations.AlterField(
            model_name="product",
            name="orig_product",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="boulange.product", verbose_name="Produit d'origine"),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name="Prix"),
        ),
        migrations.AlterField(
            model_name="product",
            name="ref",
            field=models.CharField(max_length=20, unique=True, verbose_name="Référence"),
        ),
        migrations.AlterField(
            model_name="productline",
            name="ingredient",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="boulange.ingredient", verbose_name="Ingrédient"),
        ),
        migrations.AlterField(
            model_name="productline",
            name="product",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="raw_ingredients", to="boulange.product", verbose_name="Produit"),
        ),
        migrations.AlterField(
            model_name="productline",
            name="quantity",
            field=models.FloatField(verbose_name="Quantité"),
        ),
        migrations.AlterField(
            model_name="settings",
            name="name",
            field=models.CharField(max_length=200, unique=True, verbose_name="Nom"),
        ),
        migrations.AlterField(
            model_name="settings",
            name="value",
            field=models.CharField(max_length=200, verbose_name="Valeur"),
        ),
        migrations.AlterField(
            model_name="weeklydelivery",
            name="active",
            field=models.BooleanField(default=True, verbose_name="Actif"),
        ),
        migrations.AlterField(
            model_name="weeklydelivery",
            name="allowed_customers",
            field=models.ManyToManyField(blank=True, related_name="private_weekly_deliveries", to=settings.AUTH_USER_MODEL, verbose_name="Clients autorisés"),
        ),
        migrations.AlterField(
            model_name="weeklydelivery",
            name="batch_target",
            field=models.CharField(choices=[("SAME_DAY", "Le jour même"), ("PREVIOUS_DAY", "La veille")], default="SAME_DAY", max_length=20, verbose_name="Jour de fabrication"),
        ),
        migrations.AlterField(
            model_name="weeklydelivery",
            name="customer",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name="Client"),
        ),
        migrations.AlterField(
            model_name="weeklydelivery",
            name="day_of_week",
            field=models.IntegerField(choices=[(0, "lundi"), (1, "mardi"), (2, "mercredi"), (3, "jeudi"), (4, "vendredi"), (5, "samedi"), (6, "dimanche")], verbose_name="Jour de la semaine"),
        ),
        migrations.AlterField(
            model_name="weeklydelivery",
            name="notes",
            field=models.TextField(blank=True, null=True, verbose_name="Notes"),
        ),
        migrations.AlterField(
            model_name="weeklydelivery",
            name="online_payment",
            field=models.BooleanField(default=True, verbose_name="Paiement en ligne"),
        ),
        migrations.AlterField(
            model_name="weeklydelivery",
            name="public_delivery_point",
            field=models.BooleanField(default=True, verbose_name="Point de retrait public"),
        ),
    ]
