# Generated by Django 5.2.15 on 2026-09-25 15:20

import uuid

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boulange", "0028_alter_checkout_options_alter_customer_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SignupRequest",
            fields=[
                ("token", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
            ],
            options={
                "verbose_name": "Demande de création de compte",
                "verbose_name_plural": "Demandes de création de compte",
            },
        ),
    ]
